from django import forms

CITIES = [
    ('abbey-street', 'Abbey Street'),
    ('Adamstown', 'Adamstown'), ('amiens-street', 'Amiens Street'),
    ('arbour-hill', 'Arbour Hill'), ('ard-na-greine', 'Ard Na Greine'),
    ('Artane', 'Artane'), ('Ashtown', 'Ashtown'),
    ('Aylesbury', 'Aylesbury'), ('Ayrfield', 'Ayrfield'),
    ('baggot-street', 'Baggot Street'), ('Balbriggan', 'Balbriggan'),
    ('Baldonnel', 'Baldonnel'), ('Baldoyle', 'Baldoyle'),
    ('Balgriffin', 'Balgriffin'),
    ('Ballinteer', 'Ballinteer'), ('Ballsbridge', 'Ballsbridge'),
    ('Ballybough', 'Ballybough'),
    ('Ballyboughal', 'Ballyboughal'), ('Ballybrack', 'Ballybrack'),
    ('Ballycoolin', 'Ballycoolin'),('Ballycullen', 'Ballycullen'),
    ('Ballyfermot', 'Ballyfermot'), ('Ballymount', 'Ballymount'),
    ('Ballymun', 'Ballymun'), ('Balrothery', 'Balrothery'),
    ('Balscadden', 'Balscadden'), ('Bayside', 'Bayside'),
    ('Beaumont', 'Beaumont'),
    ('Belmayne', 'Belmayne'), ('Blackhorse-Ave', 'Blackhorse Ave'),
    ('Blackpitts', 'Blackpitts'), ('Blackrock', 'Blackrock'),
    ('Blanchardstown', 'Blanchardstown'), ('Bluebell', 'Bluebell'),
    ('Bohernabreena', 'Bohernabreena'), ('Booterstown', 'Booterstown'),
    ('Brittas', 'Brittas'), ('Broadstone', 'Broadstone'),
    ('Cabinteely', 'Cabinteely'), ('Cabra', 'Cabra'),
    ('Carpenterstown', 'Carpenterstown'), ('Carrickmines', 'Carrickmines'),
    ('Castleknock', 'Castleknock'), ('Chapelizod', 'Chapelizod'),
    ('cherry-orchard', 'Cherry Orchard'),('Cherrywood', 'Cherrywood'),
    ('Christchurch', 'Christchurch'),('Churchtown', 'Churchtown'),
    ('Citywest', 'Citywest'),('Clarehall', 'Clarehall'),
    ('Clondalkin', 'Clondalkin'),('Clonee', 'Clonee'),
    ('Clongriffin', 'Clongriffin'),('Clonliffe', 'Clonliffe'),
    ('Clonshaugh', 'Clonshaugh'),('Clonsilla', 'Clonsilla'),
    ('Clonskeagh', 'Clonskeagh'),('Clontarf', 'Clontarf'),
    ('Coolmine', 'Coolmine'), ('Coolock', 'Coolock'),
    ('Crumlin', 'Crumlin'), ('Dalkey', 'Dalkey'),
    ('dame-street', 'Dame Street'), ('Darndale', 'Darndale'),
    ('Dartry', 'Dartry'), ('Deansgrange', 'Deansgrange'),
    ('Docklands', 'Docklands'), ('dolphins-barn', 'Dolphins Barn'),
    ('Donabate', 'Donabate'), ('Donaghmede', 'Donaghmede'),
    ('Donnybrook', 'Donnybrook'), ('Donnycarney', 'Donnycarney'),
    ('dorset-street', 'Dorset Street'), ('Drimnagh', 'Drimnagh'),
    ('Drumcondra', 'Drumcondra'), ('dun-laoghaire', 'Dun Laoghaire'),
    ('Dundrum', 'Dundrum'), ('east-wall', 'East Wall'),
    ('Fairview', 'Fairview'), ('Finglas', 'Finglas'),
    ('Firhouse', 'Firhouse'), ('Foxrock', 'Foxrock'),
    ('Garristown', 'Garristown'), ('Glasnevin', 'Glasnevin'),
    ('Glasthule', 'Glasthule'), ('Glenageary', 'Glenageary'),
    ('Goatstown', 'Goatstown'), ('Gormanston', 'Gormanston'),
    ('Grand-Canal-Dk', 'Grand Canal Dk'), ('Griffith-Ave', 'Griffith Ave'),
    ('harold-s-cross', 'Harold\'s Cross'),('Hollystown', 'Hollystown'),
    ('Howth', 'Howth'), ('IFSC', 'IFSC'),
    ('Inchicore', 'Inchicore'), ('Irishtown', 'Irishtown'),
    ('Islandbridge', 'Islandbridge'),('Kilbarrack', 'Kilbarrack'),
    ('Killester', 'Killester'), ('Killiney', 'Killiney'),
    ('Kilmacud', 'Kilmacud'), ('Kilmainham', 'Kilmainham'),
    ('Kilnamanagh', 'Kilnamanagh'), ('Kilternan', 'Kilternan'),
    ('Kiltipper', 'Kiltipper'), ('Kimmage', 'Kimmage'),
    ('Kingswood', 'Kingswood'), ('Kinsealy', 'Kinsealy'),
    ('Knocklyon', 'Knocklyon'), ('Leopardstown', 'Leopardstown'),
    ('Loughlinstown', 'Loughlinstown'), ('Loughshinny', 'Loughshinny'),
    ('Lucan', 'Lucan'), ('Lusk', 'Lusk'),
    ('Malahide', 'Malahide'),('Marino', 'Marino'),
    ('Marlborough-Street', 'Marlborough Street'),
    ('Merrion', 'Merrion'), ('Merrion Square', 'Merrion Square'),
    ('Milltown', 'Milltown'), ('Monkstown', 'Monkstown'),
    ('Mount-Merrion', 'Mount Merrion'), ('Mountjoy-Square', 'Mountjoy Square'),
    ('Mulhuddart', 'Mulhuddart'), ('Naas-Road', 'Naas Road'),
    ('Naul', 'Naul'), ('Navan-Road', 'Navan Road'),
    ('Newcastle', 'Newcastle'), ('North-Circular-Road', 'North Circular Road'),
    ('North-City-Centre', 'North City Centre'), ('North-Strand', 'North Strand'),
    ('North-Wall', 'North Wall'), ('Northern-Cross', 'Northern Cross'),
    ('Oldbawn', 'Oldbawn'), ('Ongar', 'Ongar'),
    ('Palmerstown', 'Palmerstown'), ('Park-West', 'Park West'),
    ('Perrystown', 'Perrystown'), ('Phibsboro', 'Phibsboro'), ('Poppintree', 'Poppintree'),
    ('Portmarnock', 'Portmarnock'), ('Portobello', 'Portobello'), ('Raheny', 'Raheny'),
    ('Ranelagh', 'Ranelagh'), ('Rathcoole', 'Rathcoole'), ('Rathfarnham', 'Rathfarnham'),
    ('Rathgar', 'Rathgar'), ('Rathmichael', 'Rathmichael'), ('Rathmines', 'Rathmines'),
    ('Red-Cow-Roundabout', 'Red-Cow-Roundabout'), ('Rialto', 'Rialto'),
    ('Ringsend', 'Ringsend'), ('Rolestown', 'Rolestown'),
    ('Rush', 'Rush'), ('Saggart', 'Saggart'), ('Sallynoggin', 'Sallynoggin'),
    ('Sandycove', 'Sandycove'), ('Sandyford', 'Sandyford'), ('Sandymount', 'Sandymount'),
    ('Santry', 'Santry'), ('Shankill', 'Shankill'), ('Skerries', 'Skerries'),
    ('Smithfield', 'Smithfield'), ('South-Circular-Road', 'South-Circular-Road'),
    ('South-City-Centre', 'South City Centre'), ('St-Margarets', 'St Margarets'),
    ('Stepaside', 'Stepaside'), ('Stillorgan', 'Stillorgan'), ('Stoneybatter', 'Stoneybatter'),
    ('Strawberry-Beds', 'Strawberry Beds'), ('Sutton', 'Sutton'),
    ('Swords', 'Swords'), ('Talbot Street', 'Talbot Street'),
    ('Tallaght', 'Tallaght'), ('Temple-Bar', 'Temple Bar'),
    ('Templeogue', 'Templeogue'), ('Terenure', 'Terenure'),
    ('The-Coombe', 'The Coombe'), ('The-Ward', 'The Ward'),
    ('Ticknock', 'Ticknock'), ('Tyrrelstown', 'Tyrrelstown'),
    ('Walkinstown', 'Walkinstown'), ('Whitehall', 'Whitehall'),
    ('Windy-Arbour', 'Windy Arbour')
]

HOUSE_TYPE = [
    ('Any', 'Any'),
    ('Apartment ', 'Apartment'),
    ('Terraced House ', 'Terraced House'),
    ('Semi-Detached ', 'Semi-Detached'),
    ('Detached ', 'Detached'),
    ('Bungalow ', 'Bungalow'),
    ('Country House ', 'Country House'),
    ('Studio ', 'Studio')
]

class PropertySearchForm(forms.Form):
    city = forms.CharField(label='Area', widget= forms.Select(choices = CITIES))
    house_type = forms.MultipleChoiceField(label='House Type', required = False,
                                           widget=forms.CheckboxSelectMultiple, choices = HOUSE_TYPE)
