# Generated by Django 3.1.2 on 2020-12-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Prop',
        ),
    ]
