# Generated by Django 3.1.2 on 2021-02-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20210204_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestProperty',
        ),
    ]
