# Generated by Django 3.1.2 on 2021-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20210208_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproperty',
            name='baths',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testproperty',
            name='beds',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
