# Generated by Django 3.1.2 on 2021-03-14 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20210303_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent', models.CharField(max_length=100)),
                ('beds', models.CharField(max_length=100, null=True)),
                ('baths', models.CharField(max_length=100, null=True)),
                ('propertyType', models.CharField(max_length=100)),
            ],
        ),
    ]
