# Generated by Django 3.1.2 on 2021-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_auto_20210321_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
