# Generated by Django 3.1.2 on 2021-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_housing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
